### PR TITLE
Updated dependencies (zendframework/stdlib ~3.0)

### PR DESCRIPTION
**Pull request by rang501**

### CODE REVIEW

**Comment by tobre6** [comment]
Thanks for the PR @rang501 , please see why the tests aren't passing.
Also I think that we should move on and upgrade it to support ZF3. So the PR is good. What do you think @rammrain ?

**Comment by rang501** [comment]
I think I got it working, but the php 5.5 build fails because it is not supported by the newer zend libraries.

**Comment by tobre6** [comment]
Perhaps we should drop the php 5.5 support after all @rammrain ?

**Comment by rammrain** [comment]
I think we can drop PHP 5.5 support with a new major version, but this should be then clearly documented in readme and composer.json

**Comment by tobre6** [comment]
Thank you for the PR, new release: https://github.com/BitWeb/id-services/releases/tag/2.0.0

**Pull request merged**
